### ISSUE TITLE
Cadastro de eventos

### ISSUE THREAD

**Issue by pedrosino** [pedrosino/abcm#2]
- [ ] nome
- [ ] data_inicio
- [ ] data_fim
- [ ] local
- [ ] cidade,estado
- [ ] site
- [ ] site_externo (boolean)

Estes próximos só são usados se não tiver site externo
- [ ] introdução
- [ ] modalidades
- [ ] cronograma
- [ ] local
- [ ] inscrições
- [ ] resultados/midia

**Comment by pitalig** [comment]
@pedrosino Estou preparando essa parte. Não consegui colocar "assignee" para mim, acho que você precisa me colocar como colaborador no repositório.
